table Calculations
	lineageTag: b5e4d897-ac44-40fa-a863-7c4c02a3cd9f

	measure COGS = SUMX('classicmodels orderdetails','classicmodels orderdetails'[quantityOrdered]*RELATED('classicmodels products'[buyPrice]))
		lineageTag: a7d7745c-2542-4bbe-90a2-2493f0bd67ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AvgInventory = AVERAGE('classicmodels products'[quantityInStock])
		lineageTag: ef59fc14-92aa-473b-8ab6-6d42a1d7d1b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure StockRotation = DIVIDE([COGS],[AvgInventory],0)
		lineageTag: ea11ccb6-bd46-4aea-91ba-bf23512a5891

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Revenue = SUMX('classicmodels orderdetails','classicmodels orderdetails'[quantityOrdered]*'classicmodels orderdetails'[priceEach])
		lineageTag: 06eb14d2-b58e-4009-a274-eb98c1f082d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Calculations = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

