table Orders
	lineageTag: 325e2ad7-527b-499d-984b-f4cc90dc19fe

	column ' Shipping Data'
		dataType: string
		lineageTag: c776b1de-0833-421f-baaf-206277c03096
		summarizeBy: none
		sourceColumn: " Shipping Data"

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 1c101a6d-f2b9-4620-b102-7173c08657f8
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: 6e7bb811-e0b0-4144-96d2-3b7bec880b40
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 845c2a02-7537-457f-bcb2-f42607c17503
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		lineageTag: d607377b-503e-46f5-8517-0517fa49b470
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		lineageTag: 55708a5e-f70d-4f7f-a3ab-ce69b1abfbf0
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: 75a2a294-16fa-4283-8190-5fbcc02708cf
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 9c7b32eb-5d6c-4130-9b0b-34a2d1ec2281
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: a23841f0-d505-4bd0-a10d-04fd57b113fc
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: ba1b1a15-068e-4ef8-986c-9835399e0dfd
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 06a7ac36-ac81-4ab7-97fd-1fc7c8d697fc
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: e78b897a-2101-4fe7-a748-3c13716dfeb0
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column13
		dataType: string
		lineageTag: 30863265-8db2-42d4-8ab2-c37f8db0993f
		summarizeBy: none
		sourceColumn: Column13

		annotation SummarizationSetBy = Automatic

	column Column14
		dataType: string
		lineageTag: fd60edc3-d031-44f2-a5f5-1ae54412c4c8
		summarizeBy: none
		sourceColumn: Column14

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: c94cab41-5d35-4a58-bccf-0ead2696c46b
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: c89f95aa-2af0-40f7-a17c-9a8344d4619c
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	column Column17
		dataType: string
		lineageTag: d2105c97-3e83-44a6-bf73-626f4a20557b
		summarizeBy: none
		sourceColumn: Column17

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 88f99b89-5274-4cd3-b11b-cbf4db66d824
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: 0c01ab64-4198-4dff-90d0-8530bb49b87c
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	column Column20
		dataType: string
		lineageTag: 20a9cdd6-3b0a-4d0f-8b6e-cc9536d38aec
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: 40fee0fe-42c7-4fd2-9046-977639da9dd8
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	column Column22
		dataType: string
		lineageTag: 9f394337-dc46-4fdc-8820-dd39d95a9674
		summarizeBy: none
		sourceColumn: Column22

		annotation SummarizationSetBy = Automatic

	column Column23
		dataType: string
		lineageTag: d8e09f93-6c81-4c4f-8b75-3b7368a25560
		summarizeBy: none
		sourceColumn: Column23

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: 2a6f5e5e-61ae-4746-9cbb-db8a68aec910
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	column Column25
		dataType: string
		lineageTag: d6b61146-ac5b-49ff-b082-9ab464a1852f
		summarizeBy: none
		sourceColumn: Column25

		annotation SummarizationSetBy = Automatic

	column 'Order Year' = ('Orders'[Column3])
		lineageTag: 1d50dbc8-602a-4084-9381-fc0fd21074b1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\qnrit\OneDrive\Desktop\W6_V1 CreatePivotTables.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{" Shipping Data", type text}, {"Column2", type any}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type any}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

